FROM node:9-alpine

RUN mkdir /src
ADD ./ /src
WORKDIR /src/api

# RUN npm install -g yarn
# RUN chmod +x /usr/local/lib/node_modules/yarn/bin/yarn.js
# Remove the version of yarn that is coming with node:8 & Install latest yarn
RUN rm -f /usr/local/bin/yarn && \
  curl -o- -L https://yarnpkg.com/install.sh | bash && \
  chmod +x ~/.yarn/bin/yarn && \
  ln -s ~/.yarn/bin/yarn /usr/local/bin/yarn
RUN pwd
RUN ls -l

RUN yarn install
